export const COUNTRIES_SELECT_COUNTRY = "COUNTRIES/SELECT_COUNTRY";

export const AREAS_SELECT_AREA = "AREAS/SELECT_AREA";

export const CATEGORIES_SELECT_CATEGORY = 'CATEGORIES/SELECT_CATEGORY';

export const BRANCHES_SELECT_BRANCH = 'BRANCHES/SELECT_BRANCH';

export const CART_ADD_CART_ITEM = 'CART/ADD_CART_ITEM';

export const CART_REMOVE_CART_ITEM = 'CART/REMOVE_CART_ITEM';

export const CART_UPDATE_CART_ITEM_COUNT = 'CART/UPDATE_CART_ITEM_COUNT';

export const AUTH_SIGNUP = "AUTH/SIGN_UP";

export const AUTH_LOGIN = "AUTH/LOGIN";

export const AUTH_LOGOUT = "AUTH/LOGOUT";
